[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "degrid"
version = "0.1.0"
description = "PyQt6 desktop application for processing and visualizing FITS astronomy images."
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Roman Byrtus" },
  { name = "Daniel Satýnek" },
  { name = "Hana Druckmüllerová" },
  { name = "Shadia Habbal" }
]
license = { text = "BSD-2-Clause" }  # replace if you choose a different license
keywords = ["astronomy", "fits", "image processing", "pyqt", "gui"]
dependencies = [
  "PyQt6",
  "matplotlib",
  "numpy",
  "scipy",
  "astropy"
]

[project.urls]
Homepage = "https://github.com/Romanuccio/Degrid"
Repository = "https://github.com/Romanuccio/Degrid"
Issues = "https://github.com/Romanuccio/Degrid/issues"

[tool.setuptools]
py-modules = ["main", "FFPS"]